/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.device.myjavaservice.controller;
import com.device.myjavaservice.MyJavaService;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController	
@RequestMapping(value = "/myJava",  produces = {"application/json", "application/xml"})
public class MyJavaController{

	@Autowired	
	private MyJavaService myJavaService;

	@RequestMapping(value = "/sampleJavaOperation" ,  produces = "application/json", method = RequestMethod.GET )
	public String sampleJavaOperation(@RequestParam(value="name", required=false)String name )   {
        
            return myJavaService.sampleJavaOperation(name);
	}
} 